#-------------------------------------------------------------------------------------------------------------------#
#							  MyCommand Commands config file (last update v5.6.4)									#
#																													#
#  Plugin Documentation : https://dev.bukkit.org/projects/mycommand/pages/getstarted    							#
#  Spigot https://www.spigotmc.org/resources/mycommand.22272/  Bukkit : https://dev.bukkit.org/projects/mycommand/	#
#																													#																									#
#	How to make a command :	(See an example command below)															#
#		First, decide your command name placing it in the first row (no duplicates!)  "mycommand:"					#
#		Now set the "command:" field. This will trigger the command. Don't forget the '/' before your command.		#
#		So, now select your command type from a predefined list putting it after "type" line						#
#	COMMAND TYPE LIST :																								#
#		TEXT , BROADCAST_TEXT, RAW_TEXT , BROADCAST_RAW_TEXT, ALIAS , RUN_COMMAND , RUN_CONSOLE , RUN_COMMAND_TASK  #
#       RUN_COMMAND_RANDOM , RUN_CONSOLE_RANDOM , RUN_AS_OPERATOR , ADD_PERMISSION , ADD_COST , WARMUP , COOLDOWN   #
#       WARMUP_AND_COOLDOWN , BLOCK_PATTERN ,  BAR_API_TEXT , BAR_API_BROADCAST_TEXT , CALL_URL , EXP_BAR			#
#       ICON_MENU , MERCHANT , SCOREBOARD , BUNGEE_TP , TITLE, BROADCAST_TITLE , ACTION_BAR , BROADCAST_ACTION_BAR	#
#		HOLOGRAPHIC_TEXT , BROADCAST_HOLOGRAPHIC_TEXT , LIVE_CHAT , BOOK , RAW_BOOK, ANVIL_GUI						#
#																													#
#	If your command is "TEXT" type, you can put multiple line of text below this parameter							#
#	You can do the same thing with the "RUN_COMMAND" type, but instead of text, puts commands in this list			#
#	For delayed command(s) add $delay$ before the command in runcmd Example : - $delay$/list						#
#	Set delay time with delaytimer: 5 (5 = seconds) | 																#
#   If you are using the Vault plugin, you can put the "cost: 123.0" with this line. 								#
#	You can customize your permission node by placing "permission-node:" field in a command							#
#	Change the permission error message with "permission-error:" or create a command without permission required	#
#   with "permission-required: false". Custom error-message for invalid args, use "error-message:"					#
#   You can use itemcost : 'ID:AMOUNT' for set a cost with items. 													#
#   Register REAL commands putting "register: true" below the command. Those are recognized from other plugins.    	#
#   With register commands you can use the "tab_completer: - Hi - Hello!"											#
#   For Scripts and more features, find more on the bukkitdev page													#
#-------------------------------------------------------------------------------------------------------------------#
menu_page1:
  command: /menus
  type: ICON_MENU
  text:
  - 'POSITION:ITEM_NAME:ITEMDATA:COMMAND/MESSAGE:TITLE:DESCRIPTION;MULTILINES'
  - 'ITEM_NAME can also be ITEM_NAME;ENCHANTMENT_NAME;LEVEL'
  iconmenu_title: '&c整地メニュー'
  iconmenu_size: 36
  iconmenu_commands:
  - 0:PLAYER_HEAD%$player:0:%stayopen%:$playerの頭だよろこべよ
  - 3:WOODEN_AXE:0:%openiconmenu%/menu_hogo:保護の詳細(未実装):保護の詳細ページを開きます
  - 7:NETHER_STAR:0:%openiconmenu%/menu_idou:&bワールド移動メニュー
  - 8:BEACON:0:/mvspawn $player:ワールドのSpawnに戻ります
  - 19:COMPASS:0:/rtp:ランダムテレポート
  - 35:PLAYER_HEAD%eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTliZjMyOTJlMTI2YTEwNWI1NGViYTcxM2FhMWIxNTJkNTQxYTFkODkzODgyOWM1NjM2NGQxNzhlZDIyYmYifX19:22:%openiconmenu%/menu2:2ページ
  cost: 0
  delaytimer: 0

menu_page2:
  command: /menu2
  type: ICON_MENU
  text:
  - 'POSITION:ITEM_NAME:ITEMDATA:COMMAND/MESSAGE:TITLE:DESCRIPTION;MULTILINES'
  - 'ITEM_NAME can also be ITEM_NAME;ENCHANTMENT_NAME;LEVEL'
  iconmenu_title: '&c整地メニュー'
  iconmenu_size: 36
  iconmenu_commands:
  - 8:NETHER_STAR:0:/mvtp $player hub:Hubに戻ります
  - 27:PLAYER_HEAD%eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQ2OWUwNmU1ZGFkZmQ4NGU1ZjNkMWMyMTA2M2YyNTUzYjJmYTk0NWVlMWQ0ZDcxNTJmZGM1NDI1YmMxMmE5In19fQ==:11:%openiconmenu%/menus:1ページ
  cost: 0
  delaytimer: 0


hogomenu_page1:
  command: /menu_hogo
  type: ICON_MENU
  text:
  - 'POSITION:ITEM_NAME:ITEMDATA:COMMAND/MESSAGE:TITLE:DESCRIPTION;MULTILINES'
  - 'ITEM_NAME can also be ITEM_NAME;ENCHANTMENT_NAME;LEVEL'
  iconmenu_title: '&c保護メニュー(未実装)'
  iconmenu_size: 9
  iconmenu_commands:
  - 0:WOODEN_AXE:0:%stayopen%:保護の取り方:隣にある木の斧を選択します;範囲を選択して金の斧を押します;/rg claim [保護エリア名] [自分のminecraft名]を実行すると保護が取れます
  - 1:WOODEN_AXE:0://wand:保護を取るためのツール:保護を取るための木の斧を召喚します
  - 2:GOLDEN_AXE:0://expand vert:保護の範囲を設定します:保護の範囲を岩盤から上限の高さまで引き上げます
  cost: 0
  delaytimer: 0

idoumenu_page1:
  command: /menu_idou
  type: ICON_MENU
  text:
  - 'POSITION:ITEM_NAME:ITEMDATA:COMMAND/MESSAGE:TITLE:DESCRIPTION;MULTILINES'
  - 'ITEM_NAME can also be ITEM_NAME;ENCHANTMENT_NAME;LEVEL'
  iconmenu_title: '&c移動メニュー'
  iconmenu_size: 9
  iconmenu_commands:
  - 0:GRASS_BLOCK:0:/mvtp $player seitiwa-rudo1:&f整地ワールド(地上):&8整地ワールド(地上)にワープします
  - 1:NETHERRACK:0:/mvtp $player seitineza-:&f整地ワールド(ネザー):&8整地ワールド(ネザー)にワープします
  - 2:END_STONE:0:/mvtp $player seitiend:&f整地ワールド(エンド):&8整地ワールド(エンド)にワープします
  - 7:OAK_PLANKS:0:/mvtp $player kenntiku:&f建築ワールド:&8建築ワールドにワープします
  - 8:CHEST:0:/mvtp $player shop:&fショップワールド:&8ショップワールドにワープします
  cost: 0
  delaytimer: 0

Random_Teleport:
  command: /rtp
  type: RUN_CONSOLE
  runcmd:
  - /effect give $player minecraft:resistance 4 99
  - /spreadplayers ~ ~ 0 500 false $player
  - /tell $player ランダムテレポートをしました。
